config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-sepia-grouse.sh
        container: qc.acc_zippy-burgundy-harrier
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-puce-reindeer.sh
        container: qc.doc_clammy-auburn-bloodhound
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-sapphire-orangutan.sh
        container: qc.doc_nippy-ochre-robin
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-viridian-squid.sh
        container: qc.doc_foggy-alizarin-buzzard
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cerulean-uguisu.sh
        container: qc.lic_pasty-xanthic-malamute
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-harlequin-wolverine.sh
        container: qc.met_cheeky-magnolia-numbat
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-magnolia-millipede.sh
        container: qc.sec_ugly-mustard-spoonbill
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-rust-kangaroo.sh
        container: qc.sty_bluesy-emerald-duck
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-azure-bloodhound.sh
        container: qc.sty_paltry-lime-anteater
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-smalt-uguisu.sh
        container: qc.sty_scaly-russet-octopus
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-seashell-bear.sh
        container: qc.ver_hazy-green-indri
timeout: 5400
