config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-chocolate-swan.sh
        container: qc.acc_flimsy-chestnut-frog
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cardinal-goat.sh
        container: qc.doc_slaphappy-malachite-snail
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-green-earwig.sh
        container: qc.doc_muzzy-beige-gerbil
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-carmine-labradoodle.sh
        container: qc.doc_fuzzy-ruby-kingfisher
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-bronze-javanese.sh
        container: qc.lic_snippy-cerise-bombay
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-bistre-tarsier.sh
        container: qc.met_leaky-jade-bee
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-asparagus-affenpinscher.sh
        container: qc.sec_beady-olive-gorilla
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-ecru-molly.sh
        container: qc.sty_zippy-denim-squirt
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-olive-barnacle.sh
        container: qc.sty_goopy-jade-bear
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-beige-nightingale.sh
        container: qc.sty_paltry-cinnamon-frigatebird
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder-training-module get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-puce-barb.sh
        container: qc.ver_muggy-burgundy-harrier
timeout: 5400
